- name: Install required system packages
  become: true
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - raspberrypi-kernel
      - raspberrypi-kernel-headers
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    state: present

- name: Update apt and install docker-ce
  become: true
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-compose
    state: latest
    update_cache: true

- name: Add benedikt to group docker
  become: true
  ansible.builtin.user:
    name: benedikt
    groups: docker
    append: yes
    register: group.changed

- name: Reboot...
  become: true
  reboot:
  when: group.changed
