- name: Install required system packages
  become: true
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - raspberrypi-kernel
      - raspberrypi-kernel-headers
    state: latest
    update_cache: true

#- name: Run expect to wait for a successful PXE boot via out-of-band CIMC
#  become: true
#  ansible.builtin.shell: |
#    mkdir -p /etc/apt/keyrings
#    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

- name: add GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/raspbian {{ ansible_distribution_release }} stable
    state: present

- name: Update apt and install docker-ce
  become: true
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-compose
    state: latest
    update_cache: true

- name: Add benedikt to group docker
  become: true
  ansible.builtin.user:
    name: ansible
    groups: docker
    append: yes
    register: group.changed

- name: Reboot...
  become: true
  reboot:
  when: group.changed
