
- name: Purge srv
  ansible.builtin.file:
    path: /srv
    state: absent


- name: Create an recursively change ownership of srv to ansible
  ansible.builtin.file:
    path: /srv
    state: directory
    recurse: yes
    owner: ansible
    group: ansible

- name: Create /srv/Z2M
  ansible.builtin.file:
    path: /srv/Z2M
    state: directory
    owner: ansible
    group: ansible

- name: Create /srv/Z2M/data      
  ansible.builtin.file:
    path: /srv/Z2M/data
    state: directory
    owner: ansible
    group: ansible



- name: Create /srv/mosquitto
  ansible.builtin.file:
    path: /srv/mosquitto 
    state: directory
    owner: ansible
    group: ansible


- name: Create /srv/mosquitto/config
  ansible.builtin.file:
    path: /srv/mosquitto/config
    state: directory
    owner: ansible
    group: ansible


- name: Create /srv/homeassistant
  ansible.builtin.file:
    path: /srv/mosquitto 
    state: directory
    owner: ansible
    group: ansible

- name: Copy Docker-Compose File
  become: true
  ansible.builtin.copy:
    src: docker-compose.yaml
    owner: ansible 
    group: ansible
    dest: /srv/


- name: Copy Z2M Configuration
  become: true
  ansible.builtin.copy:
    src: z2m-configuration
    owner: ansible 
    group: ansible
    dest: /srv/Z2M/data/configuration.yaml


- name: Copy mosquitto Configuration
  become: true
  ansible.builtin.copy:
    src: mosquitto.conf
    owner: ansible 
    group: ansible
    dest: /srv/mosquitto/config/
