#- name: Update Packages
#  hosts: localhost
#  roles:
#    - AptUpdate

- name: Reset Lab
  hosts: localhost
  tasks:
  
    - name: Stop Containers
      become: true
      ansible.builtin.command: 'docker kill nginx'
      ignore_errors: true
      
    - name: Stop Containers
      become: true
      ansible.builtin.command: 'docker kill mosquitto'
      ignore_errors: true
      
    - name: Stop Containers
      become: true
      ansible.builtin.command: 'docker kill zigbee2mqtt'
      ignore_errors: true

- name: Redeploy the Lab
  hosts: localhost
  roles:
    - ZigBeeLab
